import { z } from 'zod';

export const RiskTierLabelSchema = z.enum([
  'ultra_conservative',
  'conservative',
  'stable_yield',
  'moderate',
  'balanced',
  'growth',
  'aggressive',
  'degen',
  'ultra_degen',
]);

export type RiskTierLabel = z.infer<typeof RiskTierLabelSchema>;

export const RiskTierNumberSchema = z.union([
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
  z.literal(8),
  z.literal(9),
]);

export type RiskTierNumber = z.infer<typeof RiskTierNumberSchema>;

export const MeteoraPoolTypeSchema = z.enum(['stable', 'bluechip', 'volatile', 'memecoin']);
export const MeteoraPositionStyleSchema = z.enum(['two_sided', 'one_sided_sol', 'bid_ask']);
export const MeteoraRangeTypeSchema = z.enum(['wide', 'medium', 'tight', 'ultra_tight']);
export const MeteoraDepositTokenSchema = z.enum(['both', 'sol', 'usdc']);

export const TierConfigSchema = z.object({
  tier: RiskTierNumberSchema,
  label: RiskTierLabelSchema,
  capital_allocation_pct: z.number().min(0).max(1),
  max_position_size_usd: z.number().positive(),
  min_position_size_usd: z.number().positive(),
  max_concurrent_positions: z.number().int().positive(),
  allowed_protocols: z.array(z.string()).min(1),
  preferred_protocols: z.array(z.string()).min(1),
  meteora_pool_types: z.array(MeteoraPoolTypeSchema),
  meteora_position_style: MeteoraPositionStyleSchema,
  meteora_bin_step: z.number().int().min(1).max(200),
  meteora_total_bins: z.number().int().min(20).max(70),
  meteora_range_type: MeteoraRangeTypeSchema,
  meteora_deposit_token: MeteoraDepositTokenSchema,
  min_pool_tvl_usd: z.number().nonnegative(),
  max_pool_tvl_usd: z.number().positive(),
  min_volume_24h_usd: z.number().nonnegative(),
  require_volume_spike: z.boolean(),
  volume_spike_multiplier: z.number().positive(),
  require_price_momentum: z.boolean(),
  target_apy_pct: z.number().nonnegative(),
  take_profit_pct: z.number(),
  stop_loss_pct: z.number(),
  max_hold_hours: z.number().positive(),
  check_interval_minutes: z.number().int().positive(),
  max_il_tolerance_pct: z.number().nonnegative(),
  min_fee_apr_pct: z.number().nonnegative(),
  require_human_approval: z.boolean(),
  emergency_exit_on_rug: z.boolean(),
  score_weight_apy: z.number().min(0).max(1),
  score_weight_volume: z.number().min(0).max(1),
  score_weight_tvl: z.number().min(0).max(1),
  score_weight_momentum: z.number().min(0).max(1),
  score_weight_il_risk: z.number().min(0).max(1),
}).superRefine((value, ctx) => {
  const totalWeight =
    value.score_weight_apy +
    value.score_weight_volume +
    value.score_weight_tvl +
    value.score_weight_momentum +
    value.score_weight_il_risk;

  if (Math.abs(totalWeight - 1) > 0.001) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ['score_weight_apy'],
      message: `Tier ${value.tier} score weights must sum to 1.0, got ${totalWeight.toFixed(3)}`,
    });
  }
});

export type TierConfig = z.infer<typeof TierConfigSchema>;

const rawTierConfigs = {
  1: {
    tier: 1,
    label: 'ultra_conservative',
    capital_allocation_pct: 0.0,
    max_position_size_usd: 500,
    min_position_size_usd: 50,
    max_concurrent_positions: 2,
    allowed_protocols: ['kamino_lending', 'marginfi'],
    preferred_protocols: ['kamino_lending'],
    meteora_pool_types: [],
    meteora_position_style: 'two_sided',
    meteora_bin_step: 1,
    meteora_total_bins: 20,
    meteora_range_type: 'wide',
    meteora_deposit_token: 'both',
    min_pool_tvl_usd: 10_000_000,
    max_pool_tvl_usd: 999_999_999,
    min_volume_24h_usd: 1_000_000,
    require_volume_spike: false,
    volume_spike_multiplier: 1.0,
    require_price_momentum: false,
    target_apy_pct: 8.0,
    take_profit_pct: 0.0,
    stop_loss_pct: -0.03,
    max_hold_hours: 720,
    check_interval_minutes: 60,
    max_il_tolerance_pct: 0.5,
    min_fee_apr_pct: 3.0,
    require_human_approval: true,
    emergency_exit_on_rug: true,
    score_weight_apy: 0.4,
    score_weight_volume: 0.1,
    score_weight_tvl: 0.3,
    score_weight_momentum: 0.05,
    score_weight_il_risk: 0.15,
  },
  2: {
    tier: 2,
    label: 'conservative',
    capital_allocation_pct: 0.5,
    max_position_size_usd: 200,
    min_position_size_usd: 50,
    max_concurrent_positions: 4,
    allowed_protocols: ['kamino_lending', 'marginfi', 'jito', 'meteora_dlmm'],
    preferred_protocols: ['kamino_lending', 'jito'],
    meteora_pool_types: ['stable'],
    meteora_position_style: 'two_sided',
    meteora_bin_step: 5,
    meteora_total_bins: 30,
    meteora_range_type: 'wide',
    meteora_deposit_token: 'both',
    min_pool_tvl_usd: 5_000_000,
    max_pool_tvl_usd: 999_999_999,
    min_volume_24h_usd: 500_000,
    require_volume_spike: false,
    volume_spike_multiplier: 1.0,
    require_price_momentum: false,
    target_apy_pct: 15.0,
    take_profit_pct: 0.0,
    stop_loss_pct: -0.05,
    max_hold_hours: 168,
    check_interval_minutes: 60,
    max_il_tolerance_pct: 2.0,
    min_fee_apr_pct: 8.0,
    require_human_approval: true,
    emergency_exit_on_rug: true,
    score_weight_apy: 0.35,
    score_weight_volume: 0.15,
    score_weight_tvl: 0.25,
    score_weight_momentum: 0.1,
    score_weight_il_risk: 0.15,
  },
  3: {
    tier: 3,
    label: 'stable_yield',
    capital_allocation_pct: 0.0,
    max_position_size_usd: 200,
    min_position_size_usd: 50,
    max_concurrent_positions: 4,
    allowed_protocols: ['kamino_lending', 'marginfi', 'meteora_dlmm'],
    preferred_protocols: ['meteora_dlmm', 'kamino_lending'],
    meteora_pool_types: ['stable', 'bluechip'],
    meteora_position_style: 'two_sided',
    meteora_bin_step: 10,
    meteora_total_bins: 40,
    meteora_range_type: 'medium',
    meteora_deposit_token: 'both',
    min_pool_tvl_usd: 2_000_000,
    max_pool_tvl_usd: 999_999_999,
    min_volume_24h_usd: 200_000,
    require_volume_spike: false,
    volume_spike_multiplier: 1.5,
    require_price_momentum: false,
    target_apy_pct: 25.0,
    take_profit_pct: 0.0,
    stop_loss_pct: -0.08,
    max_hold_hours: 72,
    check_interval_minutes: 30,
    max_il_tolerance_pct: 5.0,
    min_fee_apr_pct: 12.0,
    require_human_approval: true,
    emergency_exit_on_rug: true,
    score_weight_apy: 0.3,
    score_weight_volume: 0.2,
    score_weight_tvl: 0.2,
    score_weight_momentum: 0.15,
    score_weight_il_risk: 0.15,
  },
  4: {
    tier: 4,
    label: 'moderate',
    capital_allocation_pct: 0.0,
    max_position_size_usd: 150,
    min_position_size_usd: 30,
    max_concurrent_positions: 5,
    allowed_protocols: ['meteora_dlmm'],
    preferred_protocols: ['meteora_dlmm'],
    meteora_pool_types: ['bluechip'],
    meteora_position_style: 'two_sided',
    meteora_bin_step: 25,
    meteora_total_bins: 50,
    meteora_range_type: 'medium',
    meteora_deposit_token: 'both',
    min_pool_tvl_usd: 500_000,
    max_pool_tvl_usd: 50_000_000,
    min_volume_24h_usd: 100_000,
    require_volume_spike: false,
    volume_spike_multiplier: 2.0,
    require_price_momentum: false,
    target_apy_pct: 40.0,
    take_profit_pct: 0.1,
    stop_loss_pct: -0.1,
    max_hold_hours: 48,
    check_interval_minutes: 20,
    max_il_tolerance_pct: 8.0,
    min_fee_apr_pct: 18.0,
    require_human_approval: true,
    emergency_exit_on_rug: true,
    score_weight_apy: 0.3,
    score_weight_volume: 0.25,
    score_weight_tvl: 0.15,
    score_weight_momentum: 0.2,
    score_weight_il_risk: 0.1,
  },
  5: {
    tier: 5,
    label: 'balanced',
    capital_allocation_pct: 0.3,
    max_position_size_usd: 125,
    min_position_size_usd: 30,
    max_concurrent_positions: 6,
    allowed_protocols: ['meteora_dlmm'],
    preferred_protocols: ['meteora_dlmm'],
    meteora_pool_types: ['bluechip', 'volatile'],
    meteora_position_style: 'bid_ask',
    meteora_bin_step: 50,
    meteora_total_bins: 60,
    meteora_range_type: 'medium',
    meteora_deposit_token: 'both',
    min_pool_tvl_usd: 200_000,
    max_pool_tvl_usd: 20_000_000,
    min_volume_24h_usd: 50_000,
    require_volume_spike: false,
    volume_spike_multiplier: 2.0,
    require_price_momentum: false,
    target_apy_pct: 60.0,
    take_profit_pct: 0.15,
    stop_loss_pct: -0.12,
    max_hold_hours: 24,
    check_interval_minutes: 15,
    max_il_tolerance_pct: 12.0,
    min_fee_apr_pct: 25.0,
    require_human_approval: true,
    emergency_exit_on_rug: true,
    score_weight_apy: 0.25,
    score_weight_volume: 0.3,
    score_weight_tvl: 0.1,
    score_weight_momentum: 0.25,
    score_weight_il_risk: 0.1,
  },
  6: {
    tier: 6,
    label: 'growth',
    capital_allocation_pct: 0.0,
    max_position_size_usd: 100,
    min_position_size_usd: 25,
    max_concurrent_positions: 8,
    allowed_protocols: ['meteora_dlmm'],
    preferred_protocols: ['meteora_dlmm'],
    meteora_pool_types: ['volatile'],
    meteora_position_style: 'one_sided_sol',
    meteora_bin_step: 75,
    meteora_total_bins: 65,
    meteora_range_type: 'tight',
    meteora_deposit_token: 'sol',
    min_pool_tvl_usd: 100_000,
    max_pool_tvl_usd: 10_000_000,
    min_volume_24h_usd: 25_000,
    require_volume_spike: true,
    volume_spike_multiplier: 2.5,
    require_price_momentum: true,
    target_apy_pct: 100.0,
    take_profit_pct: 0.2,
    stop_loss_pct: -0.12,
    max_hold_hours: 12,
    check_interval_minutes: 10,
    max_il_tolerance_pct: 15.0,
    min_fee_apr_pct: 40.0,
    require_human_approval: true,
    emergency_exit_on_rug: true,
    score_weight_apy: 0.2,
    score_weight_volume: 0.35,
    score_weight_tvl: 0.05,
    score_weight_momentum: 0.3,
    score_weight_il_risk: 0.1,
  },
  7: {
    tier: 7,
    label: 'aggressive',
    capital_allocation_pct: 0.0,
    max_position_size_usd: 75,
    min_position_size_usd: 20,
    max_concurrent_positions: 10,
    allowed_protocols: ['meteora_dlmm'],
    preferred_protocols: ['meteora_dlmm'],
    meteora_pool_types: ['volatile', 'memecoin'],
    meteora_position_style: 'one_sided_sol',
    meteora_bin_step: 100,
    meteora_total_bins: 70,
    meteora_range_type: 'tight',
    meteora_deposit_token: 'sol',
    min_pool_tvl_usd: 50_000,
    max_pool_tvl_usd: 5_000_000,
    min_volume_24h_usd: 10_000,
    require_volume_spike: true,
    volume_spike_multiplier: 3.0,
    require_price_momentum: true,
    target_apy_pct: 150.0,
    take_profit_pct: 0.25,
    stop_loss_pct: -0.13,
    max_hold_hours: 8,
    check_interval_minutes: 5,
    max_il_tolerance_pct: 20.0,
    min_fee_apr_pct: 60.0,
    require_human_approval: true,
    emergency_exit_on_rug: true,
    score_weight_apy: 0.15,
    score_weight_volume: 0.4,
    score_weight_tvl: 0.05,
    score_weight_momentum: 0.35,
    score_weight_il_risk: 0.05,
  },
  8: {
    tier: 8,
    label: 'degen',
    capital_allocation_pct: 0.2,
    max_position_size_usd: 50,
    min_position_size_usd: 15,
    max_concurrent_positions: 12,
    allowed_protocols: ['meteora_dlmm'],
    preferred_protocols: ['meteora_dlmm'],
    meteora_pool_types: ['memecoin'],
    meteora_position_style: 'bid_ask',
    meteora_bin_step: 125,
    meteora_total_bins: 70,
    meteora_range_type: 'ultra_tight',
    meteora_deposit_token: 'sol',
    min_pool_tvl_usd: 10_000,
    max_pool_tvl_usd: 150_000,
    min_volume_24h_usd: 5_000,
    require_volume_spike: true,
    volume_spike_multiplier: 3.0,
    require_price_momentum: true,
    target_apy_pct: 200.0,
    take_profit_pct: 0.3,
    stop_loss_pct: -0.15,
    max_hold_hours: 4,
    check_interval_minutes: 3,
    max_il_tolerance_pct: 25.0,
    min_fee_apr_pct: 80.0,
    require_human_approval: true,
    emergency_exit_on_rug: true,
    score_weight_apy: 0.1,
    score_weight_volume: 0.45,
    score_weight_tvl: 0.0,
    score_weight_momentum: 0.4,
    score_weight_il_risk: 0.05,
  },
  9: {
    tier: 9,
    label: 'ultra_degen',
    capital_allocation_pct: 0.0,
    max_position_size_usd: 30,
    min_position_size_usd: 10,
    max_concurrent_positions: 15,
    allowed_protocols: ['meteora_dlmm'],
    preferred_protocols: ['meteora_dlmm'],
    meteora_pool_types: ['memecoin'],
    meteora_position_style: 'bid_ask',
    meteora_bin_step: 200,
    meteora_total_bins: 70,
    meteora_range_type: 'ultra_tight',
    meteora_deposit_token: 'sol',
    min_pool_tvl_usd: 5_000,
    max_pool_tvl_usd: 50_000,
    min_volume_24h_usd: 2_000,
    require_volume_spike: true,
    volume_spike_multiplier: 5.0,
    require_price_momentum: true,
    target_apy_pct: 500.0,
    take_profit_pct: 0.4,
    stop_loss_pct: -0.15,
    max_hold_hours: 2,
    check_interval_minutes: 2,
    max_il_tolerance_pct: 30.0,
    min_fee_apr_pct: 100.0,
    require_human_approval: true,
    emergency_exit_on_rug: true,
    score_weight_apy: 0.05,
    score_weight_volume: 0.5,
    score_weight_tvl: 0.0,
    score_weight_momentum: 0.4,
    score_weight_il_risk: 0.05,
  },
} as const satisfies Record<RiskTierNumber, TierConfig>;

export const DEFAULT_TIER_CONFIGS: Record<RiskTierNumber, TierConfig> = {
  1: TierConfigSchema.parse(rawTierConfigs[1]),
  2: TierConfigSchema.parse(rawTierConfigs[2]),
  3: TierConfigSchema.parse(rawTierConfigs[3]),
  4: TierConfigSchema.parse(rawTierConfigs[4]),
  5: TierConfigSchema.parse(rawTierConfigs[5]),
  6: TierConfigSchema.parse(rawTierConfigs[6]),
  7: TierConfigSchema.parse(rawTierConfigs[7]),
  8: TierConfigSchema.parse(rawTierConfigs[8]),
  9: TierConfigSchema.parse(rawTierConfigs[9]),
};

export const ALL_RISK_TIERS: RiskTierNumber[] = [1, 2, 3, 4, 5, 6, 7, 8, 9];

export function parseRiskTierNumber(value: unknown): RiskTierNumber | null {
  const parsed = RiskTierNumberSchema.safeParse(value);
  return parsed.success ? parsed.data : null;
}

export function isAggressiveTier(tier: number): boolean {
  return tier >= 7;
}

export function isConservativeTier(tier: number): boolean {
  return tier >= 1 && tier <= 3;
}

export function isActiveDlmmTier(tier: number): boolean {
  return tier >= 6;
}
